server:
  port: 1002

spring:
  application:
    name: cloud-user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: gwang

  cloud:
    zookeeper:
      connect-string: 192.168.0.106:2181

mybatis:
  type-aliases-package: com.wanggang.springcloud.entity
  mapper-locations: classpath*:mapper/*.xml