server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: order_route1  # 路由的id,没有规定规则但要求唯一,建议配合服务名
          uri: lb://cloud-order-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/order/createOrderInfo  # 断言，路径相匹配的进行路由

        - id: order_route2
          uri: lb://cloud-order-service
          predicates:
            - Path=/order/getOrderInfoById/**  #  断言,路径相匹配的进行路由
            - After=2020-09-29T22:10:15.485+08:00[Asia/Shanghai]  # 断言时间配置
           # - Cookie=username,wanggang   #  带Cookie，并且username的值为wanggang
           #- Header=X-Request-Id,\d+   #  请求头要有 X-Request-Id属性并且值为整数的正则表达式

#这里把feign做客户端
eureka:
  instance:
    instance-id: gateway-9527
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaServer7001.com:7001/eureka/,http://eurekaServer7002.com:7002/eureka/