server:
  port: 8001

spring:
  application:
    name: order-service-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: gwang

mybatis:
  type-aliases-package: com.wanggang.springcloud.entity
  mapper-locations: classpath*:mapper/*.xml

eureka:
  instance:
    hostname: OrderService8001
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
