server:
  port: 1004

spring:
  application:
    name: cloud-user-service

#这里把feign做客户端
eureka:
  instance:
    instance-id: user-1004
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaServer7001.com:7001/eureka/,http://eurekaServer7002.com:7002/eureka/

# 设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  # 指两端的服务建立连接所用的时间
  ReadTimeout: 5000
  # 指服务器响应资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志监控接口级别
    com.wanggang.springcloud.service.UserFeignService: debug