server:
  port: 8005

spring:
  application:
    name: cloud-order-hystrix-service

#这里把feign做客户端
eureka:
  instance:
    instance-id: order-8005
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaServer7001.com:7001/eureka/,http://eurekaServer7002.com:7002/eureka/